version: '2.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY_ERRORS=On
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 8000:80
    networks:
      - aplication
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - admin

  adminer:
    image: adminer:latest
    ports:
      - 8081:80
    networks:
      - admin
    depends_on:
      - mysql

networks:
  admin:
  aplication:
  other_network:

